before_script:
  - mysql -e 'create database activeuuid_test;'
  - psql -c 'create database activeuuid_test;' -U postgres

rvm:
  - 2.4.3

gemfile:
  - gemfiles/Gemfile.rails-5-1
  - gemfiles/Gemfile.rails-head

env:
  - DB=mysql
  - DB=postgresql
